export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY: "/verify",
  ADMIN: "/dashboard",
  BRAND: "/dashboard/brand",
  MODEL: "/dashboard/model",
  ADD_MODEL: "/dashboard/add-model",
  PRODUCT: "/product",
  DETAIL: "/detail/:idProduct?",
  CART: "/cart",
  PAYMENT: "/payment",
  PROFILE: "/profile",
  BILLS: "/bills",
  ERROR: "/error/:type",
  CONTACT: "/contact",
  QUESTION: "/question",
};
